using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flowly.API.Migrations
{
    /// <inheritdoc />
    public partial class UpgradeEFCore10 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Table already exists in environments where it was created outside of
            // migrations; CREATE TABLE IF NOT EXISTS makes this migration idempotent.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""AttendanceLogs"" (
                    ""Id""        integer GENERATED BY DEFAULT AS IDENTITY,
                    ""StaffId""   integer NOT NULL,
                    ""ShiftDate"" timestamp with time zone NOT NULL,
                    ""ClockIn""   timestamp with time zone,
                    ""ClockOut""  timestamp with time zone,
                    ""Note""      character varying(500),
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_AttendanceLogs"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_AttendanceLogs_Staff_StaffId""
                        FOREIGN KEY (""StaffId"") REFERENCES ""Staff"" (""Id"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_AttendanceLogs_StaffId""
                    ON ""AttendanceLogs"" (""StaffId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AttendanceLogs");
        }
    }
}
