import React, { useState, useEffect, useCallback, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { authAPI } from '../../api/auth';
import { useToast } from '../../components/shared/Toast';
import {
  Users, Mail, Phone, Eye, EyeOff, ChevronLeft,
  CheckCircle, AlertCircle, X, Save, CalendarDays,
  DollarSign, Percent, Zap, Hash, User,
} from 'lucide-react';

/* ── Constants ── */
const ALL_DAYS = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const SHIFT_HOURS = ['06:00','07:00','08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00'];
const STAFF_TYPES = ['Detailer','Receptionist','Bookkeeper','Manager','Other'];
const DEFAULT_PASSWORD = 'Detailer123!';

const DEFAULT_SKILLS = [
  'Exterior Wash & Dry','Machine Polish','Paint Correction','Ceramic Coating',
  'Paint Protection Film','Headlight Restoration','Interior Deep Clean',
  'Seat & Upholstery Care','Stain & Odor Removal','Dashboard Detailing',
  'Interior Ceramic Coat','Engine Bay Cleaning','Rim & Wheel Detailing','Glass Sealing',
];

function loadSkills() {
  try { return JSON.parse(localStorage.getItem('adminSkills'))?.map(s => s.name) || DEFAULT_SKILLS; }
  catch { return DEFAULT_SKILLS; }
}

const PRISM_CSS = `
@keyframes holo-sweep{0%{background-position:0% 50%}100%{background-position:300% 50%}}
@keyframes cta-rainbow-glow{0%,100%{box-shadow:0 0 0 1.5px rgba(255,80,80,.42),0 0 22px rgba(255,165,0,.15)}33%{box-shadow:0 0 0 1.5px rgba(0,200,255,.42),0 0 22px rgba(160,0,255,.15)}66%{box-shadow:0 0 0 1.5px rgba(0,255,120,.42),0 0 22px rgba(255,0,100,.15)}}
@keyframes card-enter{from{transform:translateY(14px) scale(.988);opacity:0}to{transform:translateY(0) scale(1);opacity:1}}
.spectrum-line{height:1.5px;background:linear-gradient(90deg,transparent 0%,rgba(255,0,100,.80) 12%,rgba(255,165,0,.85) 24%,rgba(255,255,0,.85) 36%,rgba(0,255,100,.85) 48%,rgba(0,150,255,.85) 60%,rgba(150,0,255,.80) 72%,transparent 85%);background-size:200% 100%;animation:holo-sweep 5s linear infinite;opacity:.40}
.cta-prism-glow{animation:cta-rainbow-glow 5s ease-in-out infinite}
.card-stagger{animation:card-enter .52s cubic-bezier(.22,1,.36,1) both}
.field-input{width:100%;padding:10px 14px;border-radius:12px;border:1px solid var(--border-color);background:var(--surface-bg);color:var(--text-color);font-size:.875rem;transition:border-color .2s,box-shadow .2s;outline:none}
.field-input:focus{border-color:rgba(200,169,107,.65);box-shadow:0 0 0 3px rgba(200,169,107,.12)}
.field-label{display:block;font-size:.68rem;font-weight:700;letter-spacing:.20em;text-transform:uppercase;color:var(--muted-color);margin-bottom:7px}
`;

export default function AdminAddStaff() {
  const navigate = useNavigate();
  const toast = useToast();
  const shortCodeRef = useRef(null);

  const [form, setForm] = useState({
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    password: DEFAULT_PASSWORD,
    staffType: 'Detailer',
    shortCode: '',
    compensationType: 'Salary',
    salaryAmount: '',
    percentageRate: '',
    skills: [],
    workingDays: ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
    shiftStart: '09:00',
    shiftEnd: '18:00',
  });

  const [showPassword, setShowPassword] = useState(false);
  const [saving, setSaving] = useState(false);
  const [errors, setErrors] = useState({});

  // Short code check
  const [shortCodeStatus, setShortCodeStatus] = useState(null); // null | 'checking' | 'available' | 'taken'
  const [shortCodeSuggestions, setShortCodeSuggestions] = useState([]);
  const shortCodeTimer = useRef(null);
  const [shortCodeAutoGenerated, setShortCodeAutoGenerated] = useState(false);
  const [shortCodeManuallyEdited, setShortCodeManuallyEdited] = useState(false);
  const suggestTimer = useRef(null);

  const availableSkills = loadSkills();

  const set = (field, value) => setForm(p => ({ ...p, [field]: value }));

  // Auto-suggest short code from first + last name (debounced, only when not manually edited)
  useEffect(() => {
    clearTimeout(suggestTimer.current);
    if (shortCodeManuallyEdited) return;
    const fn = form.firstName.trim();
    const ln = form.lastName.trim();
    if (fn.length < 2 || ln.length < 2) return;
    suggestTimer.current = setTimeout(async () => {
      try {
        const { suggested } = await authAPI.suggestShortCode(fn, ln);
        if (!shortCodeManuallyEdited) {
          set('shortCode', suggested);
          setShortCodeAutoGenerated(true);
          setShortCodeStatus(null);
          clearTimeout(shortCodeTimer.current);
          shortCodeTimer.current = setTimeout(() => checkShortCode(suggested), 300);
        }
      } catch {
        // silent — user can still type manually
      }
    }, 600);
    return () => clearTimeout(suggestTimer.current);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [form.firstName, form.lastName, shortCodeManuallyEdited]);

  const checkShortCode = useCallback(async (code) => {
    if (!code || code.length < 2) { setShortCodeStatus(null); return; }
    setShortCodeStatus('checking');
    try {
      const result = await authAPI.checkShortCode(code);
      setShortCodeStatus(result.available ? 'available' : 'taken');
      setShortCodeSuggestions(result.suggestions || []);
    } catch {
      setShortCodeStatus(null);
    }
  }, []);

  const handleShortCodeChange = (e) => {
    const raw = e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 4);
    set('shortCode', raw);
    setShortCodeManuallyEdited(true);
    setShortCodeAutoGenerated(false);
    setShortCodeStatus(null);
    clearTimeout(shortCodeTimer.current);
    if (raw.length >= 2) {
      shortCodeTimer.current = setTimeout(() => checkShortCode(raw), 600);
    }
  };

  const toggleDay = (day) =>
    set('workingDays', form.workingDays.includes(day)
      ? form.workingDays.filter(d => d !== day)
      : [...form.workingDays, day]);

  const toggleSkill = (skill) =>
    set('skills', form.skills.includes(skill)
      ? form.skills.filter(s => s !== skill)
      : [...form.skills, skill]);

  const validate = () => {
    const e = {};
    if (!form.firstName.trim()) e.firstName = 'Required';
    if (!form.lastName.trim()) e.lastName = 'Required';
    if (!form.email.trim() || !form.email.includes('@')) e.email = 'Valid email required';
    if (!form.phone.trim()) e.phone = 'Required';
    if (!form.password || form.password.length < 8) e.password = 'Min 8 characters';
    if (form.shortCode && form.shortCode.length < 2) e.shortCode = 'Min 2 characters';
    if (shortCodeStatus === 'taken') e.shortCode = 'Short code already taken';
    if (form.compensationType === 'Salary' && form.salaryAmount !== '' && Number(form.salaryAmount) < 0)
      e.salaryAmount = 'Must be positive';
    if (form.compensationType === 'Percentage') {
      const r = Number(form.percentageRate);
      if (!form.percentageRate || r < 0 || r > 100) e.percentageRate = '0–100 required';
    }
    if (form.workingDays.length === 0) e.workingDays = 'Select at least one day';
    return e;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const errs = validate();
    if (Object.keys(errs).length > 0) { setErrors(errs); return; }
    setErrors({});

    try {
      setSaving(true);
      await authAPI.createWorker({
        firstName: form.firstName.trim(),
        lastName: form.lastName.trim(),
        email: form.email.trim(),
        phone: form.phone.trim(),
        password: form.password,
        staffType: form.staffType,
        shortCode: form.shortCode || null,
        compensationType: form.compensationType,
        salaryAmount: form.compensationType === 'Salary' && form.salaryAmount !== '' ? Number(form.salaryAmount) : null,
        percentageRate: form.compensationType === 'Percentage' ? Number(form.percentageRate) : null,
        skills: form.skills,
      });
      toast.success(`${form.firstName} ${form.lastName} added successfully!`);
      navigate('/admin/staff');
    } catch (err) {
      const msg = err?.response?.data?.message || 'Failed to add staff member';
      toast.error(msg);
      if (msg.toLowerCase().includes('email')) setErrors(p => ({ ...p, email: msg }));
      if (msg.toLowerCase().includes('short code')) setErrors(p => ({ ...p, shortCode: msg }));
    } finally {
      setSaving(false);
    }
  };

  const inp = 'field-input';

  return (
    <>
      <style>{PRISM_CSS}</style>
      <div className="min-h-screen py-10 relative" style={{
        background: 'radial-gradient(circle at 7% 6%,rgba(200,169,107,.05) 0%,transparent 38%),radial-gradient(circle at 93% 92%,rgba(14,165,160,.04) 0%,transparent 32%)',
      }}>
        <div className="container mx-auto px-4 max-w-3xl relative z-10 space-y-6">

          {/* Header */}
          <div>
            <button onClick={() => navigate('/admin/staff')}
              className="flex items-center gap-2 text-sm text-[var(--muted-color)] hover:text-[var(--text-color)] transition mb-4">
              <ChevronLeft size={16} /> Back to Staff
            </button>
            <div className="flex items-center gap-3 mb-1">
              <div className="w-9 h-9 rounded-xl flex items-center justify-center"
                style={{ background:'rgba(200,169,107,.12)', border:'1px solid rgba(200,169,107,.24)' }}>
                <Users size={16} style={{ color:'#c8a96b' }} />
              </div>
              <h1 className="premium-heading text-3xl font-bold text-[var(--heading-color)]">Add Staff Member</h1>
            </div>
            <p className="text-sm text-[var(--muted-color)] ml-12">Fill in all required fields to onboard a new team member.</p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">

            {/* Personal Info */}
            <div className="glass-card p-7 card-stagger">
              <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--muted-color)] mb-5">Personal Information</p>
              <div className="mb-4"><div className="spectrum-line" /></div>
              <div className="grid md:grid-cols-2 gap-5">
                <div>
                  <label className="field-label">First Name *</label>
                  <input className={inp} value={form.firstName} onChange={e => set('firstName', e.target.value)} placeholder="e.g. Mohamed" />
                  {errors.firstName && <p className="text-rose-400 text-xs mt-1">{errors.firstName}</p>}
                </div>
                <div>
                  <label className="field-label">Last Name *</label>
                  <input className={inp} value={form.lastName} onChange={e => set('lastName', e.target.value)} placeholder="e.g. Al-Harbi" />
                  {errors.lastName && <p className="text-rose-400 text-xs mt-1">{errors.lastName}</p>}
                </div>
                <div>
                  <label className="field-label">Email *</label>
                  <div className="relative">
                    <Mail size={13} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--muted-color)]" />
                    <input type="email" className={inp} style={{ paddingLeft:'2.25rem' }} value={form.email} onChange={e => set('email', e.target.value)} placeholder="staff@example.com" />
                  </div>
                  {errors.email && <p className="text-rose-400 text-xs mt-1">{errors.email}</p>}
                </div>
                <div>
                  <label className="field-label">Phone *</label>
                  <div className="relative">
                    <Phone size={13} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--muted-color)]" />
                    <input type="tel" className={inp} style={{ paddingLeft:'2.25rem' }} value={form.phone} onChange={e => set('phone', e.target.value)} placeholder="+974XXXXXXXX" />
                  </div>
                  {errors.phone && <p className="text-rose-400 text-xs mt-1">{errors.phone}</p>}
                </div>
                <div>
                  <label className="field-label">Default Password *</label>
                  <div className="relative">
                    <input type={showPassword ? 'text' : 'password'} className={inp} style={{ paddingRight:'2.5rem' }} value={form.password} onChange={e => set('password', e.target.value)} />
                    <button type="button" onClick={() => setShowPassword(p => !p)} className="absolute right-3 top-1/2 -translate-y-1/2 text-[var(--muted-color)]">
                      {showPassword ? <EyeOff size={16}/> : <Eye size={16}/>}
                    </button>
                  </div>
                  {errors.password && <p className="text-rose-400 text-xs mt-1">{errors.password}</p>}
                </div>
                <div>
                  <label className="field-label">Staff Type</label>
                  <select className={inp} value={form.staffType} onChange={e => set('staffType', e.target.value)}>
                    {STAFF_TYPES.map(t => <option key={t} value={t}>{t}</option>)}
                  </select>
                </div>
              </div>
            </div>

            {/* Short Code */}
            <div className="glass-card p-7 card-stagger">
              <div className="flex items-center gap-2 mb-1">
                <Hash size={14} style={{ color:'#c8a96b' }} />
                <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--muted-color)]">Short Name / Code</p>
              </div>
              <p className="text-xs text-[var(--muted-color)] mb-4 ml-6">4 uppercase characters. Used for stamp in/out. Must be unique.</p>
              <div className="flex items-start gap-3">
                <div className="flex-1">
                  <div className="relative">
                    <input
                      ref={shortCodeRef}
                      className={inp}
                      value={form.shortCode}
                      onChange={handleShortCodeChange}
                      maxLength={4}
                      placeholder="e.g. MOMA"
                      style={{
                        fontFamily: 'monospace', fontWeight: 700, fontSize: '1.1rem', letterSpacing: '.15em',
                        borderColor: shortCodeStatus === 'taken' ? 'rgba(248,113,113,.6)' : shortCodeStatus === 'available' ? 'rgba(34,197,94,.6)' : undefined,
                      }}
                    />
                    {shortCodeStatus === 'checking' && (
                      <div className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 border-2 border-primary border-t-transparent rounded-full animate-spin" />
                    )}
                    {shortCodeStatus === 'available' && <CheckCircle size={16} className="absolute right-3 top-1/2 -translate-y-1/2 text-green-400" />}
                    {shortCodeStatus === 'taken' && <X size={16} className="absolute right-3 top-1/2 -translate-y-1/2 text-rose-400" />}
                  </div>
                  {shortCodeStatus === 'taken' && (
                    <p className="text-rose-400 text-xs mt-1">Short code already taken.</p>
                  )}
                  {shortCodeStatus === 'available' && (
                    <p className="text-green-400 text-xs mt-1">
                      Available!{shortCodeAutoGenerated && <span className="text-[var(--muted-color)] ml-2">auto-generated</span>}
                    </p>
                  )}
                  {errors.shortCode && <p className="text-rose-400 text-xs mt-1">{errors.shortCode}</p>}
                </div>
              </div>
              {shortCodeSuggestions.length > 0 && (
                <div className="mt-3">
                  <p className="text-xs text-[var(--muted-color)] mb-2">Suggestions:</p>
                  <div className="flex flex-wrap gap-2">
                    {shortCodeSuggestions.map(s => (
                      <button key={s} type="button"
                        onClick={() => { set('shortCode', s); setShortCodeStatus('available'); setShortCodeSuggestions([]); }}
                        className="px-3 py-1 rounded-lg text-xs font-bold font-mono border border-primary/40 text-primary hover:bg-primary/10 transition">
                        {s}
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Compensation */}
            <div className="glass-card p-7 card-stagger">
              <div className="flex items-center gap-2 mb-4">
                <DollarSign size={14} style={{ color:'#c8a96b' }} />
                <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--muted-color)]">Compensation</p>
              </div>
              <div className="flex gap-3 mb-5">
                {['Salary','Percentage'].map(type => (
                  <button key={type} type="button"
                    onClick={() => set('compensationType', type)}
                    className={`flex-1 py-2.5 rounded-xl text-sm font-bold border transition ${form.compensationType === type ? 'bg-primary text-white border-primary' : 'border-[var(--border-color)] text-[var(--text-color)] hover:bg-white/5'}`}>
                    {type === 'Salary' ? <><DollarSign size={14} className="inline mr-1.5" />Monthly Salary</> : <><Percent size={14} className="inline mr-1.5" />Per Job %</>}
                  </button>
                ))}
              </div>
              {form.compensationType === 'Salary' ? (
                <div>
                  <label className="field-label">Monthly Salary (QAR)</label>
                  <input type="number" min={0} step={50} className={inp} value={form.salaryAmount} onChange={e => set('salaryAmount', e.target.value)} placeholder="e.g. 2500 (optional, set later)" />
                  {errors.salaryAmount && <p className="text-rose-400 text-xs mt-1">{errors.salaryAmount}</p>}
                </div>
              ) : (
                <div>
                  <label className="field-label">Percentage Rate per Completed Job (%) *</label>
                  <input type="number" min={0} max={100} step={0.5} className={inp} value={form.percentageRate} onChange={e => set('percentageRate', e.target.value)} placeholder="e.g. 15" />
                  {errors.percentageRate && <p className="text-rose-400 text-xs mt-1">{errors.percentageRate}</p>}
                  <p className="text-xs text-[var(--muted-color)] mt-2">Worker earns this % of each completed job's revenue.</p>
                </div>
              )}
            </div>

            {/* Skills */}
            <div className="glass-card p-7 card-stagger">
              <div className="flex items-center gap-2 mb-4">
                <Zap size={14} style={{ color:'#c8a96b' }} />
                <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--muted-color)]">Skills</p>
                <span className="text-[10px] text-[var(--muted-color)] ml-1">({form.skills.length} selected)</span>
              </div>
              <div className="flex flex-wrap gap-2">
                {availableSkills.map(skill => {
                  const selected = form.skills.includes(skill);
                  return (
                    <button key={skill} type="button" onClick={() => toggleSkill(skill)}
                      className={`px-3 py-1.5 rounded-xl text-xs font-bold border transition ${selected ? 'bg-primary text-white border-primary' : 'border-[var(--border-color)] text-[var(--text-color)] hover:bg-white/5'}`}>
                      {selected && <CheckCircle size={11} className="inline mr-1.5" />}{skill}
                    </button>
                  );
                })}
              </div>
              <p className="text-xs text-[var(--muted-color)] mt-3">Manage the skill list at <strong>Admin → Skills</strong>.</p>
            </div>

            {/* Work Schedule */}
            <div className="glass-card p-7 card-stagger">
              <div className="flex items-center gap-2 mb-1">
                <CalendarDays size={14} style={{ color:'#c8a96b' }} />
                <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--muted-color)]">Work Schedule</p>
              </div>
              <p className="text-xs text-[var(--muted-color)] mb-5">Default shift. Per-day overrides can be set after creating the staff member.</p>

              {/* Default shift */}
              <div className="mb-5 p-4 rounded-xl border border-[var(--border-color)]" style={{ background:'rgba(200,169,107,.04)' }}>
                <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--muted-color)] mb-3">Default shift (applies unless overridden)</p>
                <div className="flex flex-wrap items-end gap-5">
                  <div>
                    <label className="field-label">Start</label>
                    <select className={inp} value={form.shiftStart} onChange={e => set('shiftStart', e.target.value)}>
                      {SHIFT_HOURS.map(h => <option key={h} value={h}>{h}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="field-label">End</label>
                    <select className={inp} value={form.shiftEnd} onChange={e => set('shiftEnd', e.target.value)}>
                      {SHIFT_HOURS.map(h => <option key={h} value={h}>{h}</option>)}
                    </select>
                  </div>
                </div>
              </div>

              {/* Per-day grid */}
              <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--muted-color)] mb-3">Days & per-day overrides</p>
              <div className="grid gap-2">
                {ALL_DAYS.map(day => {
                  const active = form.workingDays.includes(day);
                  return (
                    <div key={day}
                      className={`flex flex-col sm:flex-row sm:items-center gap-2 rounded-xl border px-3 py-2.5 transition-all ${active ? 'border-[var(--border-color)]' : 'border-dashed border-[var(--border-color)] opacity-50'}`}
                      style={active ? { background:'rgba(200,169,107,.04)' } : {}}>
                      <button type="button" onClick={() => toggleDay(day)}
                        className={`w-24 shrink-0 px-2 py-1 rounded-lg text-xs font-bold border transition-all ${active ? 'bg-primary text-white border-primary' : 'border-[var(--border-color)] bg-[var(--card-bg)] text-[var(--muted-color)]'}`}>
                        {day.slice(0,3)}
                      </button>
                      {active && (
                        <div className="flex items-center gap-2 flex-1 flex-wrap">
                          <select className={inp} value={form.shiftStart} onChange={e => set('shiftStart', e.target.value)}
                            style={{ padding:'6px 10px', fontSize:'12px' }}>
                            {SHIFT_HOURS.map(h => <option key={h} value={h}>{h}</option>)}
                          </select>
                          <span className="text-xs text-[var(--muted-color)]">to</span>
                          <select className={inp} value={form.shiftEnd} onChange={e => set('shiftEnd', e.target.value)}
                            style={{ padding:'6px 10px', fontSize:'12px' }}>
                            {SHIFT_HOURS.map(h => <option key={h} value={h}>{h}</option>)}
                          </select>
                          <span className="text-xs text-[var(--muted-color)] italic">default</span>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
              {errors.workingDays && <p className="text-rose-400 text-xs mt-3">{errors.workingDays}</p>}
            </div>

            {/* Submit */}
            <div className="flex gap-3 pb-6">
              <div className="cta-prism-glow rounded-xl">
                <button type="submit" disabled={saving}
                  className="flex items-center gap-2 bg-primary text-white px-8 py-3 rounded-xl text-sm font-bold hover:bg-primary/90 transition disabled:opacity-50">
                  {saving ? 'Adding...' : <><Save size={15}/> Add Staff Member</>}
                </button>
              </div>
              <button type="button" onClick={() => navigate('/admin/staff')}
                className="px-6 py-3 rounded-xl border border-[var(--border-color)] text-sm font-bold text-[var(--text-color)] hover:bg-white/5 transition">
                Cancel
              </button>
            </div>

          </form>
        </div>
      </div>
    </>
  );
}
